snowflake_account    = "kphkhts-rg78111"
snowflake_user       = "admin"
snowflake_role       = "ACCOUNTADMIN"
snowflake_region     = "us-east-1"
snowflake_warehouse  = "TEST_WH"
snowflake_database   = "TEST_DB"
